# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/thinpad_top.xdc

# IP: ip/fifo_generator_0_1/fifo_generator_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: ip/pll_example/pll_example.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pll_example || ORIG_REF_NAME==pll_example} -quiet] -quiet
