# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/LONGXIN/nscscc2023_mips_v2.0/fpga_template_mips_utf8_v1.0/thinpad_top.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
# IP: The module: 'mult_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/LONGXIN/nscscc2023_mips_v2.0/fpga_template_mips_utf8_v1.0/thinpad_top.srcs/sources_1/ip/mult_gen_0/mult_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/LONGXIN/nscscc2023_mips_v2.0/fpga_template_mips_utf8_v1.0/thinpad_top.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
# IP: The module: 'mult_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/LONGXIN/nscscc2023_mips_v2.0/fpga_template_mips_utf8_v1.0/thinpad_top.srcs/sources_1/ip/mult_gen_0/mult_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
